"""
持久化用户配置 — 存储在 ~/.config/kai/settings.json

支持的配置项:
  base_dir  — 工作区目录 (kai base <path>)
  cli_name  — CLI 命令名 (kai name <name>)
"""
import json
import os
import shutil
import sys
from pathlib import Path

# 配置文件路径
_CONFIG_DIR = Path.home() / ".config" / "kai"
_SETTINGS_FILE = _CONFIG_DIR / "settings.json"

# 默认值
_DEFAULTS = {
    "base_dir": "",       # 空 = 使用 CWD
    "cli_name": "kai",    # 默认命令名
}


def _ensure_config_dir():
    _CONFIG_DIR.mkdir(parents=True, exist_ok=True)


def load_settings() -> dict:
    """加载持久化配置，不存在则返回默认值"""
    if _SETTINGS_FILE.exists():
        try:
            with open(_SETTINGS_FILE, "r", encoding="utf-8") as f:
                data = json.load(f)
            # 合并默认值 (兼容旧版配置缺少新字段)
            merged = {**_DEFAULTS, **data}
            return merged
        except (json.JSONDecodeError, OSError):
            return dict(_DEFAULTS)
    return dict(_DEFAULTS)


def save_settings(settings: dict):
    """保存配置到磁盘"""
    _ensure_config_dir()
    with open(_SETTINGS_FILE, "w", encoding="utf-8") as f:
        json.dump(settings, f, indent=2, ensure_ascii=False)


# ============ 便捷接口 ============

def get_base_dir() -> str:
    """获取已保存的 base_dir (空字符串 = 未设置，使用 CWD)"""
    return load_settings().get("base_dir", "")


def set_base_dir(path: str):
    """设置并持久化 base_dir"""
    s = load_settings()
    s["base_dir"] = path
    save_settings(s)


def get_cli_name() -> str:
    """获取当前 CLI 命令名"""
    return load_settings().get("cli_name", "kai")


def set_cli_name(new_name: str):
    """
    重命名 CLI 命令:
      1. 在 bin 目录创建符号链接 new_name → 原始入口
      2. 保存到配置
    """
    old_name = get_cli_name()

    # 找到当前可执行文件所在的 bin 目录
    bin_dir = _find_bin_dir()
    if not bin_dir:
        print(f"   ⚠️ 无法定位 bin 目录，请手动创建别名:")
        print(f"      alias {new_name}='kai'")
        s = load_settings()
        s["cli_name"] = new_name
        save_settings(s)
        return False

    # 源: kai 的实际入口脚本
    src = bin_dir / "kai"
    dest = bin_dir / new_name

    if not src.exists():
        # 可能通过其他名字安装的
        src = bin_dir / "secretary"
        if not src.exists():
            src = bin_dir / old_name

    if dest.exists() or dest.is_symlink():
        dest.unlink()

    try:
        if src.exists():
            # 创建符号链接: lily → kai (或复制脚本)
            os.symlink(src, dest)
            print(f"   ✅ 已创建: {dest} → {src.name}")
        else:
            # 如果找不到源，直接创建一个小 wrapper
            _create_wrapper_script(dest)
            print(f"   ✅ 已创建入口脚本: {dest}")
    except OSError as e:
        print(f"   ⚠️ 创建链接失败: {e}")
        print(f"   💡 请手动执行: alias {new_name}='kai'")

    s = load_settings()
    s["cli_name"] = new_name
    save_settings(s)
    return True


def _find_bin_dir() -> Path | None:
    """找到 pip 安装脚本的 bin 目录"""
    # 方法1: 从 sys.executable 推断
    # venv: .../venv/bin/python → .../venv/bin/
    # system: /usr/bin/python → ~/.local/bin/ (user install)
    venv_bin = Path(sys.executable).parent
    if (venv_bin / "kai").exists() or (venv_bin / "secretary").exists():
        return venv_bin

    # 方法2: 常见的 user bin
    user_bin = Path.home() / ".local" / "bin"
    if user_bin.exists():
        if (user_bin / "kai").exists() or (user_bin / "secretary").exists():
            return user_bin

    # 方法3: 从 PATH 搜索
    for name in ["kai", "secretary"]:
        found = shutil.which(name)
        if found:
            return Path(found).parent

    return venv_bin if venv_bin.exists() else None


def _create_wrapper_script(dest: Path):
    """创建一个 Python wrapper 脚本"""
    script = f"""#!/usr/bin/env python3
# Auto-generated by kai name command
from secretary.cli import main
main()
"""
    dest.write_text(script, encoding="utf-8")
    dest.chmod(0o755)

