"""
持久化用户配置 — 按平台存储:
  Windows: %APPDATA%\\study\\settings.json
  macOS/Linux: ~/.config/study/settings.json (XDG 约定)
"""
import json
import os
import shutil
import sys
from pathlib import Path


def _config_dir() -> Path:
    if sys.platform == "win32":
        appdata = os.environ.get("APPDATA")
        if appdata:
            return Path(appdata) / "study"
    return Path.home() / ".config" / "study"


_CONFIG_DIR = _config_dir()
_SETTINGS_FILE = _CONFIG_DIR / "settings.json"

_DEFAULTS = {
    "base_dir": "",
    "cli_name": "study",
    "model": "Auto",
    "language": "zh",
}


def _ensure_config_dir():
    _CONFIG_DIR.mkdir(parents=True, exist_ok=True)


def load_settings() -> dict:
    if _SETTINGS_FILE.exists():
        try:
            data = json.loads(_SETTINGS_FILE.read_text(encoding="utf-8"))
            if isinstance(data, dict):
                return {**_DEFAULTS, **data}
        except (json.JSONDecodeError, OSError):
            pass
    return dict(_DEFAULTS)


def save_settings(settings: dict):
    _ensure_config_dir()
    _SETTINGS_FILE.write_text(
        json.dumps(settings, indent=2, ensure_ascii=False),
        encoding="utf-8",
    )


def get_base_dir() -> str:
    return load_settings().get("base_dir", "")


def set_base_dir(path: str):
    s = load_settings()
    s["base_dir"] = path
    save_settings(s)


def get_cli_name() -> str:
    return load_settings().get("cli_name", "study")


def get_model() -> str:
    return load_settings().get("model", "Auto")


def set_model(model: str):
    s = load_settings()
    s["model"] = model
    save_settings(s)


def get_language() -> str:
    raw = os.environ.get("SECRETARY_LANGUAGE", "").strip().lower()
    if raw in ("en", "zh"):
        return raw
    return load_settings().get("language", "zh") or "zh"


def set_language(lang: str):
    lang = lang.strip().lower()
    if lang not in ("en", "zh"):
        raise ValueError("language must be 'en' or 'zh'")
    s = load_settings()
    s["language"] = lang
    save_settings(s)


def set_cli_name(new_name: str):
    bin_dir = _find_bin_dir()
    if not bin_dir:
        print("   ⚠️ 无法定位 bin 目录，请手动创建别名:")
        print(f"      alias {new_name}='study'")
        s = load_settings()
        s["cli_name"] = new_name
        save_settings(s)
        return False

    def _resolve_exe(directory: Path, name: str) -> Path | None:
        for candidate in (directory / name, directory / f"{name}.exe"):
            if candidate.exists():
                return candidate
        return None

    src = _resolve_exe(bin_dir, "study") or _resolve_exe(bin_dir, "secretary")
    if src is None:
        src = bin_dir / "study"

    dest = bin_dir / (f"{new_name}.exe" if sys.platform == "win32" and str(src).lower().endswith(".exe") else new_name)
    if dest.exists() or dest.is_symlink():
        dest.unlink()

    try:
        if src.exists():
            os.symlink(src, dest)
            print(f"   ✅ 已创建: {dest} → {src.name}")
        else:
            _create_wrapper_script(dest)
            print(f"   ✅ 已创建入口脚本: {dest}")
    except OSError as e:
        print(f"   ⚠️ 创建链接失败: {e}")
        print(f"   💡 请手动执行: alias {new_name}='study'")

    s = load_settings()
    s["cli_name"] = new_name
    save_settings(s)
    return True


def _has_cli_entry(directory: Path) -> bool:
    for base in ("study", "secretary"):
        if (directory / base).exists() or (directory / f"{base}.exe").exists():
            return True
    return False


def _find_bin_dir() -> Path | None:
    venv_bin = Path(sys.executable).parent
    if _has_cli_entry(venv_bin):
        return venv_bin

    user_bin = Path.home() / ".local" / "bin"
    if user_bin.exists() and _has_cli_entry(user_bin):
        return user_bin

    if sys.platform == "win32":
        appdata = os.environ.get("APPDATA")
        if appdata:
            python_appdata = Path(appdata) / "Python"
            if python_appdata.exists():
                for sub in python_appdata.iterdir():
                    if sub.is_dir() and sub.name.startswith("Python"):
                        scripts = sub / "Scripts"
                        if scripts.exists() and _has_cli_entry(scripts):
                            return scripts

    for name in ("study", "secretary"):
        found = shutil.which(name)
        if found:
            return Path(found).parent
    return venv_bin if venv_bin.exists() else None


def _create_wrapper_script(dest: Path):
    script = """#!/usr/bin/env python3
# Auto-generated by study name command
from secretary.cli import main
main()
"""
    dest.write_text(script, encoding="utf-8")
    dest.chmod(0o755)
